// GENERATED by e2e/how-steps-place.mjs — do not edit by hand.
//
// The intrinsic size of every step picture in public/how/, so the page can reserve its box
// before a lazy image arrives. The dark twin of each step is the same size (it is the same
// card, captured twice). Regenerate with `node e2e/how-steps-place.mjs`.
export const HOW_SHOTS: Record<number, { w: number; h: number }> = {
  1: { w: 1072, h: 1044 },
  2: { w: 1072, h: 1078 },
  3: { w: 1012, h: 986 },
  4: { w: 1072, h: 798 },
  5: { w: 1072, h: 648 },
  6: { w: 1072, h: 1530 },
  7: { w: 1280, h: 896 },
};
